// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Head from "next/head";

function Page(Props) {
  Props.children;
  return React.createElement(React.Fragment, undefined, React.createElement(Head.default, {
                  children: null
                }, React.createElement("meta", {
                      content: "width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover",
                      name: "viewport"
                    }), React.createElement("title", undefined, "Bracket Factory")));
}

var make = Page;

export {
  make ,
  
}
/* react Not a pure module */
