// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$MyBlog from "../src/components/Page/Section.bs.js";

function str(prim) {
  return prim;
}

function make(param) {
  return React.createElement(Section$MyBlog.make, {
              title: "About Page",
              subtitle: "This is the about page",
              children: React.createElement("p", undefined, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam ipsa enim, officiis?")
            });
}

var $$default = make;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
