// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$MyBlog from "../src/components/Page/Section.bs.js";

function str(prim) {
  return prim;
}

function Contact(Props) {
  return React.createElement(Section$MyBlog.make, {
              title: "Contact",
              subtitle: "This is the contact page",
              children: React.createElement("p", undefined, "Lorem, ipsum dolor sit elit. Commodi alias dolorum reprehenderit placeat nam.")
            });
}

var make = Contact;

var $$default = Contact;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
