// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Hello(Props) {
  return React.createElement("div", {
              className: ""
            }, "Hello World");
}

var make = Hello;

var $$default = Hello;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
