// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$MyBlog from "../src/components/Page/Section.bs.js";

function str(prim) {
  return prim;
}

function Index(Props) {
  return React.createElement(Section$MyBlog.make, {
              title: "Bracket Factory",
              subtitle: "BF Blog built ReasonML, NextJS and Bulma CSS",
              children: null
            }, React.createElement("p", undefined, "Lorem ipsum dolor sit amet consectetur adipisicing elit.\n     In odit fugiat dolores fuga,  vel omnis quae rerum modi cumque tempora."), React.createElement("p", undefined, "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi sunt harum ullam distinctio temporibus architecto quas sequi saepe nam odio."));
}

var make = Index;

var $$default = Index;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
