// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var subtitle = Css.style(/* :: */[
      Css.color(Css.rgba(255, 255, 255, 0.7)),
      /* :: */[
        Css.fontWeight(Css.bold),
        /* :: */[
          Css.marginTop(Css.px(13)),
          /* :: */[
            Css.marginLeft(Css.px(10)),
            /* :: */[
              Css.important(Css.marginBottom(Css.px(0))),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

export {
  subtitle ,
  
}
/* subtitle Not a pure module */
