// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link from "next/link";
import * as NavbarStyles$MyBlog from "./NavbarStyles.bs.js";

function Navbar(Props) {
  return React.createElement("nav", {
              className: "hero-head"
            }, React.createElement("nav", {
                  className: NavbarStyles$MyBlog.topNavStyles,
                  id: "topnav"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: NavbarStyles$MyBlog.navbarBrand
                        }, React.createElement(Link.default, {
                              href: "/",
                              children: React.createElement("a", {
                                    className: NavbarStyles$MyBlog.subtitle
                                  }, "Up and running from Reason React and NextJS")
                            }), React.createElement("span", {
                              className: "navbar-burger"
                            }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                          className: NavbarStyles$MyBlog.navbarMenu,
                          id: "navbarMenu"
                        }, React.createElement("div", {
                              className: "navbar-end"
                            }, React.createElement("div", {
                                  className: NavbarStyles$MyBlog.navbarItem
                                }, React.createElement(Link.default, {
                                      href: "/about",
                                      children: React.createElement("a", undefined, "About")
                                    })), React.createElement("div", {
                                  className: NavbarStyles$MyBlog.navbarItem
                                }, React.createElement(Link.default, {
                                      href: "/contact",
                                      children: React.createElement("a", undefined, "Contact")
                                    })))))));
}

var make = Navbar;

export {
  make ,
  
}
/* react Not a pure module */
